Fail if test_results.xml not found after tests.

diff --git a/.github/workflows/build-web.yml b/.github/workflows/build-web.yml
--- a/.github/workflows/build-web.yml
+++ b/.github/workflows/build-web.yml
@@ -53,6 +53,12 @@ jobs:
         run: |
           godot -s addons/gut/gut_cmdln.gd -d --path "$PWD" --headless -gtest=res://test/unit/test_profile_manager.gd -glog=1 -gexit
           #godot -s addons/gut/gut_cmdln.gd -d --path "$PWD" --headless --verbose -- -glog=1 -gjunit_xml_file="test_results.xml" -gconfig res://test/test_config.json -gexit
+      - name: Verify Test Results
+        run: |
+          if [ ! -f test_results.xml ]; then
+            echo "Test results not found. Failing the build."
+            exit 1
+          fi
       - name: Archive Test Results
         uses: actions/upload-artifact@v4.4.3
         with:
